USE [master]
GO

/****** Object:  Database [Dkayıt]    Script Date: 22.7.2019 14:40:08 ******/
CREATE DATABASE [Dkayıt]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Dkayıt', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\Dkayıt.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Dkayıt_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\Dkayıt_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Dkayıt] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Dkayıt].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Dkayıt] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Dkayıt] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Dkayıt] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Dkayıt] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Dkayıt] SET ARITHABORT OFF 
GO

ALTER DATABASE [Dkayıt] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Dkayıt] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Dkayıt] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Dkayıt] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Dkayıt] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Dkayıt] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Dkayıt] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Dkayıt] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Dkayıt] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Dkayıt] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Dkayıt] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Dkayıt] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Dkayıt] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Dkayıt] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Dkayıt] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Dkayıt] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Dkayıt] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Dkayıt] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Dkayıt] SET  MULTI_USER 
GO

ALTER DATABASE [Dkayıt] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Dkayıt] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Dkayıt] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Dkayıt] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Dkayıt] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Dkayıt] SET  READ_WRITE 
GO


