USE [Dkayıt]
GO

/****** Object:  Table [dbo].[TBLBASVURUFORM]    Script Date: 22.7.2019 14:59:53 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TBLBASVURUFORM](
	[BAŞVURUID] [int] IDENTITY(1,1) NOT NULL,
	[OGRENCIID] [int] NULL,
	[DERSID] [int] NULL,
 CONSTRAINT [PK_TBLBASVURUFORM] PRIMARY KEY CLUSTERED 
(
	[BAŞVURUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[TBLBASVURUFORM]  WITH CHECK ADD  CONSTRAINT [FK_TBLBASVURUFORM_TBLDERSLER] FOREIGN KEY([DERSID])
REFERENCES [dbo].[TBLDERSLER] ([DERSID])
GO

ALTER TABLE [dbo].[TBLBASVURUFORM] CHECK CONSTRAINT [FK_TBLBASVURUFORM_TBLDERSLER]
GO

ALTER TABLE [dbo].[TBLBASVURUFORM]  WITH CHECK ADD  CONSTRAINT [FK_TBLBASVURUFORM_TBLOGRENCIII] FOREIGN KEY([OGRENCIID])
REFERENCES [dbo].[TBLOGRENCIII] ([OGRID])
GO

ALTER TABLE [dbo].[TBLBASVURUFORM] CHECK CONSTRAINT [FK_TBLBASVURUFORM_TBLOGRENCIII]
GO


