USE [Dkayıt]
GO

/****** Object:  Table [dbo].[TBLDERSLER]    Script Date: 22.7.2019 15:01:51 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TBLDERSLER](
	[DERSID] [int] IDENTITY(1,1) NOT NULL,
	[DERSAD] [varchar](50) NULL,
	[DERSMINKONT] [tinyint] NULL,
	[DERSMAKSKONT] [tinyint] NULL,
 CONSTRAINT [PK_TBLDERSLER] PRIMARY KEY CLUSTERED 
(
	[DERSID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


