USE [Dkayıt]
GO

/****** Object:  Table [dbo].[TBLOGRENCIII]    Script Date: 22.7.2019 15:02:53 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TBLOGRENCIII](
	[OGRID] [int] IDENTITY(1,1) NOT NULL,
	[OGRAD] [varchar](50) NULL,
	[OGRSOYAD] [varchar](50) NULL,
	[OGRNUMARA] [varchar](50) NULL,
	[OGRFOTO] [varchar](50) NULL,
	[OGRSIFRE] [varchar](50) NULL,
	[OGRBAKIYE] [decimal](18, 2) NULL CONSTRAINT [DF_TBLOGRENCIII_OGRBAKIYE]  DEFAULT ((0)),
 CONSTRAINT [PK_TBLOGRENCIII] PRIMARY KEY CLUSTERED 
(
	[OGRID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


